src/MiniTeam/ScrumBundle/Entity/Membership.php
<?php

namespace MiniTeam\ScrumBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use MiniTeam\ScrumBundle\Entity\Project;
use MiniTeam\UserBundle\Entity\User;

/**
 * Member description
 *
 * @author Benjamin Grandfond <benjamin.grandfond@gmail.com>
 *
 * @ORM\Entity
 * @ORM\Table(name="membership")
 */
class Membership
{
    const PRODUCT_OWNER = 'product-owner';
    const SCRUM_MASTER  = 'scrum-master';
    const DEVELOPER     = 'developer';
    const MEMBER        = 'member';

    /**
     * @var Integer
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="MiniTeam\UserBundle\Entity\User", inversedBy="memberships")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $user;

    /**
     * @var Project
     *
     * @ORM\ManyToOne(targetEntity="MiniTeam\ScrumBundle\Entity\Project", inversedBy="memberships")
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id")
     */
    protected $project;

    /**
     * @var Integer
     *
     * @ORM\Column(type="string", length=20)
     */
    protected $role;

    /**
     * @param \MiniTeam\ScrumBundle\Entity\Project $project
     */
    public function setProject(Project $project)
    {
        $this->project = $project;
    }

    /**
     * @return \MiniTeam\ScrumBundle\Entity\Project
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * @param \MiniTeam\UserBundle\Entity\User $user
     */
    public function setUser(User $user)
    {
        $this->user = $user;
    }

    /**
     * @return \MiniTeam\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param int $role
     */
    public function setRole($role)
    {
        $this->role = $role;
    }

    /**
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * @return bool
     */
    public function isProductOwner()
    {
        return $this->getRole() == static::PRODUCT_OWNER;
    }

    /**
     * @return bool
     */
    public function isDeveloper()
    {
        return $this->getRole() == static::DEVELOPER;
    }

    /**
     * @return bool
     */
    public function isMember()
    {
        return $this->getRole() == static::MEMBER;
    }

    /**
     * @return bool
     */
    public function isScrumMaster()
    {
        return $this->getRole() == static::SCRUM_MASTER;
    }
}

src/MiniTeam/ScrumBundle/Controller/StoryController.php
<?php

namespace MiniTeam\ScrumBundle\Controller;

use MiniTeam\ScrumBundle\Entity\Project;
use MiniTeam\ScrumBundle\Entity\UserStory;
use MiniTeam\ScrumBundle\Entity\Comment;
use MiniTeam\ScrumBundle\Entity\Issue;
use MiniTeam\ScrumBundle\Form\UserStoryType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration as Extra;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Form;

/**
 * @author Benjamin Grandfond <benjamin.grandfond@gmail.com>
 * @author Edouard de Labareyre <edouard@melix.net>
 *
 * @Extra\Route("/{project}")
 */
class StoryController extends Controller
{

    /**
     * @Extra\Route("/us/{id}", name="story_show", requirements={"id" = "\d+"})
     * @Extra\ParamConverter("project", options={"mapping": {"project": "slug"}})
     * @Extra\Template()
     */
    public function showAction(Project $project, UserStory $story)
    {
        //remove notifications on this story
        $this->get('mini_team_scrum.notifier.story_notifier')
            ->resetStoryNotification($story, $this->getUser());

        //create comment form
        $comment = new Comment();
        $comment->setStory($story);
        $commentForm = $this->createFormBuilder($comment)
            ->add('content', 'text')
            ->getForm()
            ->createView();

        //create issue form if product owner and to validate
        $issueForm=null;
        if ($story->getStatus()=='to-validate' && $this->getUser()->isProductOwner($project)) {
            $issue = new Issue();
            $issue->setStory($story);
            $issueForm = $this->createFormBuilder($issue)
                ->add('content', 'text')
                ->getForm()
                ->createView();
        }

        return array(
            'project' => $project,
            'story' => $story,
            'commentForm' => $commentForm,
            'issueForm'=> $issueForm
        );
    }

    /**
     * @Extra\Route("/us-list/{status}", name="story_list")
     * @Extra\ParamConverter("project", options={"mapping": {"project": "slug"}})
     * @Extra\Template()
     */
    public function listAction(Project $project, $status)
    {
        //retrieve list of user stories of this project with the given status
        $stories = $this->getDoctrine()
            ->getRepository('MiniTeamScrumBundle:UserStory')
            ->findBy(
                array('status' => $status,'project' => $project),
                array('number' => 'asc')
            )
        ;

        if (count($stories) == 1) {
            $story = reset($stories);

            return $this->redirect(
                $this->generateUrl(
                    'story_show',
                    array(
                        'project' => $story->getProject()->getSlug(),
                        'id'      => $story->getId()
                    )
                )
            );
        }

        return array('project' => $project, 'stories' => $stories,'status'=>$status);
    }

    /**
     * @Extra\Route("/us/new", name="story_new")
     * @Extra\ParamConverter("project", options={"mapping": {"project": "name"}})
     * @Extra\Template()
     */
    public function newAction(Project $project, Request $request)
    {
        $story = new UserStory();
        $story->setProject($project);

        $form = $this->createForm(new UserStoryType(), $story);

        if ($request->isMethod('post')) {
            $response = $this->processForm($request, $form);

            if ($response instanceof RedirectResponse) {
                return $response;
            }
        }

        return array('project' => $project, 'form' => $form->createView());
    }

    /**
     * Process the form of a UserStory
     *
     * @param \Symfony\Component\HttpFoundation\Request $request
     * @param \Symfony\Component\Form\Form              $form
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function processForm(Request $request, Form $form)
    {
        $form->bind($request);

        if ($form->isValid()) {
            $story = $form->getData();

            $em = $this->getDoctrine()->getManager();
            $em->persist($story);
            $em->flush();

            return $this->redirect(
                $this->generateUrl(
                    'story_show',
                    array(
                        'project' => $story->getProject()->getSlug(),
                        'id' => $story->getId()
                    )
                )
            );
        }
    }

    /**
     * @Extra\Route("/us/{id}/unplan", name="story_unplan", defaults={"status": "unplan"})
     * @Extra\Route("/us/{id}/plan", name="story_plan", defaults={"status": "plan"})
     * @Extra\Route("/us/{id}/start", name="story_start", defaults={"status": "start"})
     * @Extra\Route("/us/{id}/deliver", name="story_deliver", defaults={"status": "deliver"}))
     * @Extra\Route("/us/{id}/refuse", name="story_refuse", defaults={"status": "refuse"}))
     * @Extra\Route("/us/{id}/accept", name="story_accept", defaults={"status": "accept"}))
     * @Extra\Route("/us/{id}/block", name="story_block", defaults={"status": "block"}))
     * @Extra\Route("/us/{id}/deblock", name="story_deblock", defaults={"status": "deblock"}))
     *
     * @param \MiniTeam\ScrumBundle\Entity\UserStory $story
     * @param                                        $status
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function updateStatusAction(UserStory $story, $status)
    {
        switch ($status) {
            case 'plan':
                $story->plan();
                break;
            case 'unplan':
                $story->unplan();
                break;
            case 'start':
                $story->start($this->getUser());
                break;
            case 'deliver':
                $story->deliver();
                //mark all issues as solved
                $this->getDoctrine()->getRepository('MiniTeamScrumBundle:Issue')->solveIssuesOnStory($story);
                break;
            case 'refuse':
                $story->refuse();
                break;
            case 'accept':
                $story->accept();
                break;
            case 'block':
                $story->block();
                break;
            case 'deblock':
                $story->deblock();
                break;
        }

        $em = $this->getDoctrine()->getManager();
        $em->persist($story);
        $em->flush();

        return $this->redirect($this->generateUrl('story_show', array(
            'project' => $story->getProject()->getSlug(),
            'id' => $story->getId()
        )));
    }

    /**
     * @Extra\Route("/us/{id}/delete", name="story_delete")
     *
     * @param \MiniTeam\ScrumBundle\Entity\UserStory $story
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(UserStory $story)
    {
        $project = $story->getProject();
        $status  = $story->getStatus();

        $em = $this->getDoctrine()->getManager();
        $em->remove($story);
        $em->flush();

        return $this->redirect(
            $this->generateUrl(
                'story_list',
                array(
                    'status' => $status,
                    'project' => $project,
                )
            )
        );
    }
}

src/MiniTeam/ScrumBundle/Resources/views/Story/list.html.twig
{% extends '::base.html.twig' %}

{% block body %}

    {{ render(controller('MiniTeamScrumBundle:Project:scrumBar', { 'project': project.slug, 'activeTab': status })) }}

    {% set offset = '' %}
    {% if status == constant('MiniTeam\\ScrumBundle\\Entity\\UserStory::SPRINT_BACKLOG') %}
        {% set offset = 'offset1' %}
    {% elseif status == constant('MiniTeam\\ScrumBundle\\Entity\\UserStory::DOING') %}
        {% set offset = 'offset2' %}
    {% elseif status == constant('MiniTeam\\ScrumBundle\\Entity\\UserStory::BLOCKED') %}
        {% set offset = 'offset3' %}
    {% elseif status == constant('MiniTeam\\ScrumBundle\\Entity\\UserStory::TO_VALIDATE') %}
        {% set offset = 'offset4' %}
    {% elseif status == constant('MiniTeam\\ScrumBundle\\Entity\\UserStory::DONE') %}
        {% set offset = 'offset5' %}
    {% endif %}


    <div class="row">
        <div class="span7 {{ offset }}">

            <div class="centered">
                <h3>{{ status }}</h3>
            </div>

            {%  for story in stories %}

            <a href="{{ path('story_show', { 'project': project.slug,'id': story.id }) }}">
                <div class="well user-story">
                    <p class="text-info pull-right">{{ story.points }} pts</p>
                    <span class="gray-text">#{{ story.number }}</span>
                    <span class="black-text">{{ story.title }}</span>
                </div>
            </a>

            {% endfor %}
        </div>

    </div>


{% endblock %}

src/MiniTeam/ScrumBundle/Resources/views/Story/new.html.twig
{% extends '::base.html.twig' %}

{% block body %}

    {{ render(controller('MiniTeamScrumBundle:Project:scrumBar', { 'project': project.slug,'activeTab':'us'})) }}

    <form action="{{ path('story_new',{'project':project}) }}" method="post">

        <div class="row" style="margin-top: 50px;">

            <div class="span2">
                <h4>Add story:</h4>
            </div>
            <div class="span10">
                {{ form_widget(
                    form.title,
                    {'attr': {'class':'input-block-level input-large', 'placeholder': 'Your user story'} }
                ) }}
                {# TODO avoid hard coded styles (because of bootstrap) #}
            </div>

        </div>

        <div class="row">

            <div class="span7 offset2">
                {{ form_widget(
                    form.details,
                    {'attr': {'class':'full-width', 'placeholder':'More details', 'rows':'5'} }
                ) }}
            </div>

            <div class="span3">
                {{ form_widget(form.points) }} pts
                {{ form_widget(form.status) }}
            </div>

        </div>

        {{ form_rest(form) }}

        <div class="form-actions">
            <button type="submit" class="btn btn-primary pull-right">Save</button>
            <a href="{{ path('project_show', {'project':project}) }}" type="button" class="btn">Cancel</a>
        </div>

    </form>


{% endblock %}

src/MiniTeam/ScrumBundle/Resources/views/Story/show.html.twig
{% extends '::base.html.twig' %}

{% block body %}

    {{ render(controller('MiniTeamScrumBundle:Project:scrumBar', { 'project': project.slug, 'activeTab': story.status })) }}

    <div class="well user-story">
        <div class="row">
            <div class="span12">
                <p class="lead">
                    <span class="gray-text">#{{ story.number }}</span>
                    {{ story.title }}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="span6 offset1">
                {{ story.details }}
            </div>
            <div class="span1 offset3">
                <p class="lead text-info">{{ story.points }} pts</p>
            </div>
        </div>
    </div>

    <!-- gestion du statut de la user story -->

    <div class="row">
        <div class="span2">
            {% if project.productOwner == app.user %}
                {{ block('product_owner_left_buttons') }}
            {% elseif app.user in project.developers %}
                {{ block('developer_left_buttons') }}
            {% endif %}
        </div>
        <div class="span8 centered">
            <span class="label label-info" id="status">{{ story.status }}</span>
            {% if story.isAssigned %}
                <br><span id="assignee">{{ story.assignee.username }}</span>
            {% endif %}
        </div>
        <div class="span2 align-right">
            {% if project.productOwner == app.user %}
                {{ block('product_owner_right_buttons') }}
            {% elseif app.user in project.developers %}
                {{ block('developer_right_buttons') }}
            {% endif %}
        </div>
    </div>

</div><!--container-->
<br>
<div class="story-adds">

    <!--comments thread -->
    <div class="container ">
        <div class="row">
            <div class="span6">
                <h4><i class="icon-comment"></i> Comments</h4>
                {%  for comment in story.comments %}

                    {% if project.productOwner == comment.author %}
                        {% set commentClass='alert story-comment po-comment'  %}
                    {% else %}
                        {% set commentClass='alert story-comment dev-comment' %}
                    {% endif %}

                    <div class="{{ commentClass }}">
                        <strong>{{ comment.author.username }}: </strong>{{ comment.content }}
                    </div>
                {% endfor %}



                {# TODO how to make name + input +button occupy the whole length ? #}
                {% if project.productOwner == app.user %}
                    {% set commentClass='alert story-comment po-comment'  %}
                {% else %}
                    {% set commentClass='alert story-comment dev-comment' %}
                {% endif %}
                <form action="{{ path('comment_new',{ 'project': project.slug, 'story': story.id }) }}" method="post" class="form-inline">
                    <div class="{{ commentClass }}">
                        <strong>{{ app.user.username }}: </strong>
                        {{ form_widget(
                            commentForm.content,
                            {'attr': {'class':'input-xlarge'},
                             'id':'comment-form-content'}
                        ) }}
                        {{ form_rest(commentForm) }}
                        <button type="submit" class="btn comment-button" id="comment-submit-button""><i class="icon-ok"></i></button>
                    </div>

                </form>

            </div>

            <div class="span6">
                <h4><i class="icon-fire"></i> Issues</h4>
                {% for issue in story.issues %}
                    <div class="alert issue{% if issue.opened %} alert-danger{% else %} solved-issue{% endif %}">
                        {{ issue.content }}
                    </div>
                {% endfor %}
                {% if issueForm != null %}
                <form action="{{ path('issue_new',{'project': project.slug, 'story': story.id}) }}" method="post" class="form-inline">
                    <div class="alert issue issue-form">
                        <strong>Issue: </strong>
                        {{ form_widget(
                        issueForm.content,
                        {'attr': {'class':'input-xlarge'},
                         'id':'issue-form-content'}
                        ) }}
                        {{ form_rest(issueForm) }}
                        <button type="submit" class="btn comment-button" id="issue-submit-button""><i class="icon-ok"></i></button>
                    </div>

                </form>
                {%  endif %}
            </div>

        </div>
    </div>
</div>

{% endblock %}

{% block product_owner_left_buttons %}
    {% if story.isInBacklog %}
        <a class="btn btn-danger" href="{{ path('story_delete', { 'project': project.slug, 'id': story.id }) }}" id="delete"><i class="icon-trash icon-white"></i> Delete</a>
    {% elseif story.isPlanned %}
        <a class="btn btn-inverse" id="unplan" href="{{ path('story_unplan', { 'project': project.slug, 'id': story.id }) }}"><i class="icon-fast-backward icon-white"></i> Remove from sprint</a>
    {% elseif story.isInProgress %}
        <a class="btn btn-danger" id="blocked" href="#"><i class="icon-ban-circle icon-white"></i> Blocked</a>
    {% elseif story.isDelivered %}
        <a class="btn btn-danger" id="refuse" href="{{ path('story_refuse', { 'project': project.slug, 'id': story.id }) }}"><i class="icon-thumbs-down icon-white"></i> Refuse</a>
    {% elseif story.isDone %}
        <a class="btn btn-inverse"><i class="icon-hand-up icon-white"></i> Oops</a>
    {% endif %}
{% endblock %}

{% block product_owner_right_buttons %}
    {% if story.isInBacklog %}
        <a class="btn btn-info" id="plan" href="{{ path('story_plan', { 'project': project.slug, 'id': story.id }) }}"><i class="icon-plus icon-white"></i> Plan for next sprint</a>
    {% elseif story.isBlocked %}
        <a class="btn btn-success" id="deblock" href="{{ path('story_deblock', { 'project': project.slug, 'id': story.id }) }}"><i class="icon-hand-down icon-white"></i> Deblock</a>
    {% elseif story.isDelivered %}
        <a class="btn btn-success" id="accept" href="{{ path('story_accept', { 'project': project.slug, 'id': story.id }) }}"><i class="icon-thumbs-up icon-white"></i> Accept</a>
    {% endif %}
{% endblock %}

{% block developer_left_buttons %}
    {% if story.isInProgress %}
        <a class="btn btn-danger" id="block" href="{{ path('story_block', { 'project': project.slug, 'id': story.id }) }}"><i class="icon-ban-circle icon-white"></i> Block</a>
    {% elseif story.isDone or story.isDelivered %}
        <a class="btn btn-inverse"><i class="icon-hand-up icon-white"></i> Take back</a>
    {% endif %}
{% endblock %}

{% block developer_right_buttons %}
    {% if story.isInBacklog %}
        <a class="btn btn-info" id="plan" href="{{ path('story_plan', { 'project': project.slug, 'id': story.id }) }}"><i class="icon-plus icon-white"></i> Plan for next sprint</a>
    {% elseif story.isPlanned %}
        <a class="btn btn-info" id="start" href="{{ path('story_start', { 'project': project.slug, 'id': story.id }) }}"><i class="icon-play icon-white"></i> Start</a>
    {% elseif story.isInProgress %}
        <a class="btn btn-success" id="deliver" href="{{ path('story_deliver', { 'project': project.slug, 'id': story.id }) }}"><i class="icon-ok icon-white"></i> Deliver</a>
    {% elseif story.isBlocked %}
        <a class="btn btn-success" id="deblock" href=""><i class="icon-hand-down icon-white"></i> Deblock</a>
    {% endif %}
{% endblock %}